#!/usr/bin/env python
"""V10e with 1-month production lag: fixes temporal leakage.

For eval month M, at submission time (~mid of M-1), we only know:
  - Realized DA through M-2 (complete months)
  - V6.2B signal data through M-1 (generated by pipeline)

Fix:
  1. Training window: M-9 .. M-2 (not M-8 .. M-1)
  2. binding_freq for test month M: use months < M-1 (not < M)
  3. binding_freq for training month T: use months < T-1 (not < T)

Runs both dev (36mo) and holdout (24mo).
"""
from __future__ import annotations

import gc
import json
import resource
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ml.registry_paths import registry_root, holdout_root
from ml.config import REALIZED_DA_CACHE, LTRConfig, PipelineConfig, _FULL_EVAL_MONTHS, collect_usable_months
from ml.data_loader import load_v62b_month
from ml.evaluate import aggregate_months, evaluate_ltr
from ml.features import compute_query_groups, prepare_features
from ml.train import predict_scores, train_ltr_model

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "registry"
HOLDOUT = ROOT / "holdout"

V7_DA, V7_DMIX, V7_DORI = 0.85, 0.00, 0.15  # f0 default

# Per-period-type blend weights (from blend search experiments)
BLEND_WEIGHTS: dict[str, tuple[float, float, float]] = {
    "f0": (0.85, 0.00, 0.15),
    "f1": (0.70, 0.00, 0.30),
}

V10E_FEATURES = [
    "binding_freq_1", "binding_freq_3", "binding_freq_6", "binding_freq_12",
    "binding_freq_15", "v7_formula_score", "prob_exceed_110", "constraint_limit",
    "da_rank_value",
]
V10E_MONOTONE = [1, 1, 1, 1, 1, -1, 1, 0, -1]

HOLDOUT_MONTHS = [f"{y:04d}-{m:02d}" for y in (2024, 2025) for m in range(1, 13)]


def mem_mb() -> float:
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024


def load_all_binding_sets(
    peak_type: str = "onpeak",
    cache_dir: str = REALIZED_DA_CACHE,
) -> dict[str, set[str]]:
    binding_sets: dict[str, set[str]] = {}
    if peak_type == "onpeak":
        # Legacy: onpeak files are {month}.parquet (no suffix)
        pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9].parquet"
    else:
        pattern = f"*_{peak_type}.parquet"
    for f in sorted(Path(cache_dir).glob(pattern)):
        df = pl.read_parquet(str(f))
        # Extract month from filename
        month = f.stem.replace(f"_{peak_type}", "")
        binding_sets[month] = set(df.filter(pl.col("realized_sp") > 0)["constraint_id"].to_list())
    print(f"[bf] Loaded {len(binding_sets)} months of {peak_type} binding sets")
    return binding_sets


def compute_bf(cids: list[str], month: str, bs: dict[str, set[str]], lookback: int) -> np.ndarray:
    prior = [m for m in sorted(bs.keys()) if m < month][-lookback:]
    n = len(prior)
    if n == 0:
        return np.zeros(len(cids), dtype=np.float64)
    freq = np.zeros(len(cids), dtype=np.float64)
    for m in prior:
        s = bs[m]
        for i, cid in enumerate(cids):
            if cid in s:
                freq[i] += 1
    return freq / n


def prev_month(m: str) -> str:
    """Return the month before m (e.g., '2025-03' -> '2025-02')."""
    ts = pd.Timestamp(m)
    return (ts - pd.DateOffset(months=1)).strftime("%Y-%m")


def enrich_df(
    df: pl.DataFrame, month: str, bs: dict[str, set[str]],
    lag: int = 1, blend_weights: tuple[float, float, float] | None = None,
) -> pl.DataFrame:
    """Add features. lag=1 means bf cutoff = prev_month(month), i.e., through M-2.

    This lag should ALWAYS be 1 (decision-time cutoff). The training window shift
    (which rows to include) is handled separately by the caller.
    """
    # Compute the cutoff: for lag=1, bf sees months strictly before M-1
    cutoff = month
    for _ in range(lag):
        cutoff = prev_month(cutoff)

    w_da, w_dmix, w_dori = blend_weights or (V7_DA, V7_DMIX, V7_DORI)
    cids = df["constraint_id"].to_list()
    df = df.with_columns(
        (w_da * pl.col("da_rank_value")
         + w_dmix * pl.col("density_mix_rank_value")
         + w_dori * pl.col("density_ori_rank_value")
        ).alias("v7_formula_score")
    )
    for lb in [1, 3, 6, 12, 15]:
        col_name = f"binding_freq_{lb}"
        if col_name not in df.columns:
            # Use cutoff instead of month — this is the 1-month lag
            freq = compute_bf(cids, cutoff, bs, lb)
            df = df.with_columns(pl.Series(col_name, freq))
    return df


def run_variant(
    label: str,
    eval_months: list[str],
    bs: dict[str, set[str]],
    lag: int,
    class_type: str = "onpeak",
    period_type: str = "f0",
) -> dict[str, dict]:
    blend = BLEND_WEIGHTS.get(period_type, (V7_DA, V7_DMIX, V7_DORI))
    print(f"\n[{label}] 9f, {len(eval_months)} months, lag={lag}, ptype={period_type}, "
          f"class_type={class_type}, blend={blend}")

    cfg = PipelineConfig(
        ltr=LTRConfig(
            features=V10E_FEATURES,
            monotone_constraints=V10E_MONOTONE,
            backend="lightgbm",
            label_mode="tiered",
            n_estimators=100,
            learning_rate=0.05,
            num_leaves=31,
        ),
        # Shift training window back by `lag` months
        train_months=8,
        val_months=0,
    )

    per_month: dict[str, dict] = {}

    for m in eval_months:
        t0 = time.time()

        train_month_strs = collect_usable_months(m, period_type, n_months=8)
        if not train_month_strs:
            print(f"  {m}: SKIP (insufficient training history, need ≥6 usable months)")
            continue
        train_month_strs = list(reversed(train_month_strs))  # chronological order

        # Load each training month individually (script owns month selection)
        BF_LAG = 1  # binding_freq cutoff = decision timing, always 1
        parts = []
        for tm in train_month_strs:
            try:
                part = load_v62b_month(tm, period_type, class_type)
                part = part.with_columns(pl.lit(tm).alias("query_month"))
                part = enrich_df(part, tm, bs, lag=BF_LAG, blend_weights=blend)
                parts.append(part)
            except FileNotFoundError:
                print(f"    {tm}: missing V6.2B data, skip")
        if not parts:
            print(f"  {m}: SKIP (no training data)")
            continue
        train_df = pl.concat(parts)

        # Load test month
        try:
            test_df = load_v62b_month(m, period_type, class_type)
        except FileNotFoundError:
            print(f"  {m}: SKIP (no GT data for delivery month)")
            continue
        test_df = test_df.with_columns(pl.lit(m).alias("query_month"))
        test_df = enrich_df(test_df, m, bs, lag=BF_LAG, blend_weights=blend)

        train_df = train_df.sort("query_month")
        X_train, _ = prepare_features(train_df, cfg.ltr)
        y_train = train_df["realized_sp"].to_numpy().astype(np.float64)
        groups = compute_query_groups(train_df)

        model = train_ltr_model(X_train, y_train, groups, cfg.ltr)
        X_test, _ = prepare_features(test_df, cfg.ltr)
        scores = predict_scores(model, X_test)
        actual = test_df["realized_sp"].to_numpy().astype(np.float64)

        metrics = evaluate_ltr(actual, scores)
        per_month[m] = metrics

        if hasattr(model, "feature_importance"):
            imp = model.feature_importance(importance_type="gain")
            metrics["_fi"] = dict(zip(cfg.ltr.features, [float(x) for x in imp]))

        elapsed = time.time() - t0
        n_bind = int((actual > 0).sum())
        if m == eval_months[0] or m == eval_months[-1]:
            print(f"  {m}: VC@20={metrics['VC@20']:.4f} VC@100={metrics['VC@100']:.4f} "
                  f"binding={n_bind} train={len(train_df)} ({elapsed:.1f}s)")

        del train_df, test_df, parts, X_train, y_train, groups, model, X_test, actual, scores
        gc.collect()

    # Aggregate
    clean = {m: {k: v for k, v in met.items() if not k.startswith("_")} for m, met in per_month.items()}
    agg = aggregate_months(clean)
    means = agg["mean"]
    print(f"  => VC@20={means['VC@20']:.4f} VC@50={means['VC@50']:.4f} VC@100={means['VC@100']:.4f} "
          f"R@20={means['Recall@20']:.4f} NDCG={means['NDCG']:.4f} Spearman={means['Spearman']:.4f}")

    # Feature importance avg
    fi_sums: dict[str, float] = {}
    fi_n: dict[str, int] = {}
    for met in per_month.values():
        for name, val in met.get("_fi", {}).items():
            fi_sums[name] = fi_sums.get(name, 0) + val
            fi_n[name] = fi_n.get(name, 0) + 1
    if fi_sums:
        fi_avg = {n: fi_sums[n] / fi_n[n] for n in fi_sums}
        total = sum(fi_avg.values())
        print("  Feature importance:")
        for name, avg in sorted(fi_avg.items(), key=lambda x: x[1], reverse=True):
            print(f"    {name:<25s} {avg:>8.1f} ({100 * avg / total:.1f}%)")

    return per_month


def save_results(
    label: str, per_month: dict, eval_months: list[str], dest_dir: Path,
    class_type: str = "onpeak", lag: int = 1, period_type: str = "f0",
    blend_weights: tuple[float, float, float] | None = None,
    features: list[str] | None = None,
) -> None:
    clean = {m: {k: v for k, v in met.items() if not k.startswith("_")} for m, met in per_month.items()}
    agg = aggregate_months(clean)
    d = dest_dir / label
    d.mkdir(parents=True, exist_ok=True)

    # Record actual evaluated months (not requested), to avoid metadata lies
    actual_months = sorted(clean.keys())
    skipped = sorted(set(eval_months) - set(actual_months))

    result = {
        "eval_config": {"eval_months": actual_months, "class_type": class_type,
                        "period_type": period_type, "lag": lag,
                        "note": f"{lag}-month production lag applied"},
        "per_month": clean, "aggregate": agg, "n_months": len(clean),
        "n_months_requested": len(eval_months),
        "skipped_months": skipped,
    }
    with open(d / "metrics.json", "w") as f:
        json.dump(result, f, indent=2)

    # Finding 4: persist config.json for reproducibility
    config = {
        "method": "lightgbm_regression_tiered",
        "features": features or list(V10E_FEATURES),
        "lag": lag,
        "period_type": period_type,
        "class_type": class_type,
        "label_mode": "tiered",
        "train_months": 8,
        "backend": "lightgbm_regression",
    }
    if blend_weights:
        config["blend_weights"] = {"da": blend_weights[0], "dmix": blend_weights[1], "dori": blend_weights[2]}
    with open(d / "config.json", "w") as f:
        json.dump(config, f, indent=2)

    print(f"  Saved to {d}/")


def print_comparison(labels: dict[str, dict], title: str) -> None:
    metrics_list = ["VC@10", "VC@20", "VC@25", "VC@50", "VC@100", "VC@200",
                    "Recall@10", "Recall@20", "Recall@50", "Recall@100", "NDCG", "Spearman"]

    print(f"\n{'=' * 90}")
    print(title)
    print(f"{'=' * 90}")
    header = f"{'Metric':<12}"
    for vid in labels:
        header += f" {vid:>14}"
    print(header)
    print("-" * (12 + 15 * len(labels)))

    for met in metrics_list:
        vals = {vid: m.get(met, 0) for vid, m in labels.items()}
        best = max(vals.values())
        row = f"{met:<12}"
        for vid in labels:
            v = vals[vid]
            star = "*" if v == best else " "
            row += f" {v:>13.4f}{star}"
        print(row)


def main() -> None:
    import argparse
    from ml.config import period_offset, has_period_type

    parser = argparse.ArgumentParser(description="V10e with production lag")
    parser.add_argument("--class-type", default="onpeak", choices=["onpeak", "offpeak"])
    parser.add_argument("--ptype", default="f0", help="Period type (f0, f1, f2, f3)")
    parser.add_argument("--lag", type=int, default=None,
                        help="Production lag for f0 only (default: 1). Ignored for f1+ "
                             "(collect_usable_months handles row selection).")
    parser.add_argument("--dev-only", action="store_true", help="Skip holdout")
    args = parser.parse_args()

    class_type = args.class_type
    period_type = args.ptype

    # For f0, lag controls the old shifted_eval logic (backward compat)
    # For f1+, lag is metadata only — collect_usable_months owns row selection
    effective_lag = period_offset(period_type) + 1
    if period_type == "f0":
        lag = args.lag if args.lag is not None else 1
    else:
        lag = effective_lag  # metadata only
        if args.lag is not None:
            print(f"[main] WARNING: --lag ignored for {period_type} "
                  f"(collect_usable_months handles row selection, effective_lag={effective_lag})")

    t_start = time.time()
    print(f"[main] V10e ptype={period_type}, lag={lag}, class_type={class_type}, mem={mem_mb():.0f} MB")

    bs = load_all_binding_sets(peak_type=class_type)

    if period_type == "f0":
        version_id = f"v10e-lag{lag}"  # preserve f0 naming
    else:
        version_id = "v2"  # clean version ladder for f1+

    # Compute slice directories for this (period_type, class_type)
    reg_slice = registry_root(period_type, class_type, base_dir=ROOT / "registry")
    ho_slice = holdout_root(period_type, class_type, base_dir=ROOT / "holdout")

    # Filter eval months to those where period_type exists
    dev_eval = [m for m in _FULL_EVAL_MONTHS if has_period_type(m, period_type)]
    holdout_eval = [m for m in HOLDOUT_MONTHS if has_period_type(m, period_type)]
    print(f"[main] {period_type}: {len(dev_eval)} dev months, {len(holdout_eval)} holdout months")

    # ── Dev ──
    dev_pm = run_variant(version_id, dev_eval, bs, lag=lag, class_type=class_type, period_type=period_type)
    bw = BLEND_WEIGHTS.get(period_type, BLEND_WEIGHTS["f0"])
    save_results(version_id, dev_pm, dev_eval, reg_slice, class_type=class_type, lag=lag,
                 period_type=period_type, blend_weights=bw, features=list(V10E_FEATURES))

    # ── Holdout ──
    if not args.dev_only:
        holdout_pm = run_variant(f"{version_id}-holdout", holdout_eval, bs, lag=lag, class_type=class_type, period_type=period_type)
        save_results(version_id, holdout_pm, holdout_eval, ho_slice, class_type=class_type, lag=lag,
                     period_type=period_type, blend_weights=bw, features=list(V10E_FEATURES))

    # ── Comparison ──
    v0_path = reg_slice / "v0" / "metrics.json"
    if v0_path.exists():
        v0_dev = json.load(open(v0_path))["aggregate"]["mean"]
        lag_dev_clean = {m: {k: v for k, v in met.items() if not k.startswith("_")} for m, met in dev_pm.items()}
        lag_dev = aggregate_months(lag_dev_clean)["mean"]
        labels = {"v0 (formula)": v0_dev, version_id: lag_dev}

        # Optionally add no-lag baseline if it exists
        nolag_path = reg_slice / "v10e" / "metrics.json"
        if nolag_path.exists():
            labels["v10e (no lag)"] = json.load(open(nolag_path))["aggregate"]["mean"]

        print_comparison(labels, f"DEV COMPARISON ({period_type}/{class_type}, {len(dev_eval)} months)")

        if not args.dev_only:
            v0_ho_path = ho_slice / "v0" / "metrics.json"
            if v0_ho_path.exists():
                v0_ho = json.load(open(v0_ho_path))["aggregate"]["mean"]
                lag_ho_clean = {m: {k: v for k, v in met.items() if not k.startswith("_")} for m, met in holdout_pm.items()}
                lag_ho = aggregate_months(lag_ho_clean)["mean"]
                ho_labels = {"v0 (formula)": v0_ho, version_id: lag_ho}

                nolag_ho = ho_slice / "v10e" / "metrics.json"
                if nolag_ho.exists():
                    ho_labels["v10e (no lag)"] = json.load(open(nolag_ho))["aggregate"]["mean"]

                print_comparison(ho_labels, f"HOLDOUT COMPARISON ({period_type}/{class_type}, {len(holdout_eval)} months)")
    else:
        print(f"\n[main] No v0 baseline in {reg_slice} — run v0 for {period_type}/{class_type} first")

    print(f"\n[main] Done in {time.time() - t_start:.1f}s, mem={mem_mb():.0f} MB")


if __name__ == "__main__":
    main()
